baseURL = 'https://shubham.codes/'
languageCode = 'en-us'
title = "Shubham's corner"
theme = "poison"
paginate = 10
pluralizelisttitles = false

[params]
    brand = "Shubham Kumar"
    brand_image = "/images/profile.png"
    # og_image = ""                             # path to social icon - front matter: image takes precedent, then og_image, then brand_url
    # publisher_icon = ""                       # path to publisher icon - defaults to favicon, used in schema
    # favicon = ""                              # path to favicon
    description = 'Senior SDE (PoC) <a href="https://www.greyorange.com/">GreyOrange</a>'
    dark_mode = true
    hideToc = false
    front_page_content = ["posts"]
    menu = [
        {Name = "Blog", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 3},
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "CV", URL = "/cv/", HasChildren = false}]
    github_url = "https://github.com/unresolvedcold"
    linkedin_url = "https://linkedin.com/in/schwiftycold"
    twitter_url = "https://twitter.com/schwiftycold"
    email_url = "mailto://contact@shubham.codes"

    # Plausible
    # plausible = true
    # plausible_domain = "poison.lukeorth.com"
    # plausible_script = "https://plausible.lukeorth.com/js/script.js"

    # Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
    rss_icon = true
    # Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
    rss_section = "posts"

[params.meta]
    favicon = true
[taxonomies]
    series = 'series'
    tags = 'tags'