name: Build and Deploy Hugo Website

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Install Emacs
        run: sudo apt-get install emacs

      - name: Install ox-hugo
        run: |
          emacs --batch --eval "(require 'package)" --eval "(setq package-archives '((\"org\" . \"https://orgmode.org/elpa/\") (\"melpa\" . \"https://melpa.org/packages/\") (\"gnu\" . \"https://elpa.gnu.org/packages/\")))" --eval "(package-initialize)" --eval "(package-refresh-contents)" --eval "(package-install 'ox-hugo)"

      - name: Convert Blog to Hugo Files
        run: emacs --batch -l /home/runner/.emacs.d/init.el --visit org/blog.org --funcall org-hugo-export-wim-to-md

      - name: Build Hugo Website
        run: hugo --destination public

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
